/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Error: typeof import('./src/components/Error.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    FormItem: typeof import('./src/components/FormItem.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
  }
}
